<a href="https://colab.research.google.com/github/prai96/DEEP_LEARNING/blob/main/ANN_IRIS_DATASET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# loading file

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving iris.data to iris.data
User uploaded file "iris.data" with length 4551 bytes


In [2]:
# importing data
import pandas as pd

data = pd.read_csv('/content/iris.data')

In [8]:
data.head(20)

5.1  3.5  1.4  0.2  Iris-setosa
0   4.9  3.0  1.4  0.2  Iris-setosa
1   4.7  3.2  1.3  0.2  Iris-setosa
2   4.6  3.1  1.5  0.2  Iris-setosa
3   5.0  3.6  1.4  0.2  Iris-setosa
4   5.4  3.9  1.7  0.4  Iris-setosa
5   4.6  3.4  1.4  0.3  Iris-setosa
6   5.0  3.4  1.5  0.2  Iris-setosa
7   4.4  2.9  1.4  0.2  Iris-setosa
8   4.9  3.1  1.5  0.1  Iris-setosa
9   5.4  3.7  1.5  0.2  Iris-setosa
10  4.8  3.4  1.6  0.2  Iris-setosa
11  4.8  3.0  1.4  0.1  Iris-setosa
12  4.3  3.0  1.1  0.1  Iris-setosa
13  5.8  4.0  1.2  0.2  Iris-setosa
14  5.7  4.4  1.5  0.4  Iris-setosa
15  5.4  3.9  1.3  0.4  Iris-setosa
16  5.1  3.5  1.4  0.3  Iris-setosa
17  5.7  3.8  1.7  0.3  Iris-setosa
18  5.1  3.8  1.5  0.3  Iris-setosa
19  5.4  3.4  1.7  0.2  Iris-setosa

In [7]:
data.describe()

5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [11]:
# importing libraries

import keras
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from tensorflow.keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np

In [14]:
X = data.iloc[:,0:4].values
y = data.iloc[:,4].values


from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

y1

Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [26]:
model = Sequential()
# First layer
model.add(Dense(4,input_shape=(4,), activation='relu'))
#Second layer
model.add(Dense(3, activation='softmax'))
#compiling the model
model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])
#Fitting the model
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 2s 3ms/step - loss: 2.1062 - accuracy: 0.3361
Epoch 2/100
12/12 [==============================] - 0s 3ms/step - loss: 1.9497 - accuracy: 0.3361
Epoch 3/100
12/12 [==============================] - 0s 3ms/step - loss: 1.8122 - accuracy: 0.3529
Epoch 4/100
12/12 [==============================] - 0s 3ms/step - loss: 1.6843 - accuracy: 0.4034
Epoch 5/100
12/12 [==============================] - 0s 3ms/step - loss: 1.5629 - accuracy: 0.5042
Epoch 6/100
12/12 [==============================] - 0s 3ms/step - loss: 1.4490 - accuracy: 0.5714
Epoch 7/100
12/12 [==============================] - 0s 3ms/step - loss: 1.3329 - accuracy: 0.6303
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 1.2324 - accuracy: 0.6471
Epoch 9/100
12/12 [==============================] - 0s 3ms/step - loss: 1.1420 - accuracy: 0.6387
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0480 - accuracy: 0.6303
Epoch 11/

In [27]:
#predicting the model
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.91      1.00      0.95        10
           2       1.00      0.88      0.93         8

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

[[12  0  0]
 [ 0 10  0]
 [ 0  1  7]]
